---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/exchange":
    get:
      summary: Calculate the exchange rate
      tags:
      - Exchanges
      responses:
        '200':
          description: exchange created
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  amount_converted:
                    type: float
                required:
                - success
                - message
                - amount_converted
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
